server:
  port: 81
spring:
  application:
    # 服务别名
    name: cloud-consumer-order
  cloud:
    zookeeper:
      # 注册到zookeeper地址
#      connect-string: localhost:2181
      connect-string: 120.78.144.88:2181
